import discord

def get_hero_items(url):
    error = 0xB22222
    success = 0x207325

    hero_items_string = url[92:]

    hero_item_postions = {
        2: 2,
        11: 1,
        14: 2,
        18: 2,
        22: 2,
        26: 2
    }

    hero_items_dict = {
        '1': 'Helmet of Awareness',
        '2': 'Helmet of Enlightenment',
        '3': 'Helmet of Wisdom',
        '4': 'Helmet of Regeneration',
        '5': 'Helmet of Health',
        '6': 'Helmet of Healing',
        '7': 'Helmet of the Gladiator',
        '8': 'Helmet of the Tribune',
        '9': 'Helmet of the Consul',
        'A': 'Helmet of the Horseman',
        'B': 'Helmet of the Cavalry',
        'C': 'Helmet of the Heavy cavalry',
        'D': 'Helmet of the Mercenary',
        'E': 'Helmet of the Warrior',
        'F': 'Helmet of the Archon',
        '10': 'Short sword of the Legionnaire',
        '11': 'Sword of the Legionnaire',
        '12': 'Long sword of the Legionnaire',
        '13': 'Short sword of the Praetorian',
        '14': 'Sword of the Praetorian',
        '15': 'Long sword of the Praetorian',
        '16': 'Short sword of the Imperian',
        '17': 'Sword of the Imperian',
        '18': 'Long sword of the Imperian',
        '19': 'Short sword of the Imperatoris',
        '1A': 'Sword of the Imperatoris',
        '1B': 'Long sword of the Imperatoris',
        '1C': 'Light lance of the Caesaris',
        '1D': 'Lance of the Caesaris',
        '1E': 'Heavy lance of the Caesaris',
        '1F': 'Spear of the Phalanx',
        '20': 'Pike of the Phalanx',
        '21': 'Lance of the Phalanx',
        '22': 'Short sword of the Swordsman',
        '23': 'Sword of the Swordsman',
        '24': 'Long sword of the Swordsman',
        '25': 'Short-bow of the Theutates',
        '26': 'Bow of the Theutates',
        '27': 'Long-bow of the Theutates',
        '28': 'Staff of the Druidrider',
        '29': 'Great staff of the Druidrider',
        '2A': 'Fighting-staff of the Druidrider',
        '2B': 'Light lance of the Haeduan',
        '2C': 'Lance of the Haeduan',
        '2D': 'Heavy lance of the Haeduan',
        '2E': 'Club of the Clubswinger',
        '2F': 'Mace of the Clubswinger',
        '30': 'Morning star of the Clubswinger',
        '31': 'Spear of the Spearman',
        '32': 'Spike of the Spearman',
        '33': 'Lance of the Spearman',
        '34': 'Hatchet of the Axeman',
        '35': 'Axe of the Axeman',
        '36': 'Battle axe of the Axeman',
        '37': 'Light hammer of the Paladin',
        '38': 'Hammer of the Paladin',
        '39': 'Heavy hammer of the Paladin',
        '3A': 'Short sword of the Teutonic Knight',
        '3B': 'Sword of the Teutonic Knight',
        '3C': 'Long sword of the Teutonic Knight',
        '73': 'Club of the Slave Militia',
        '74': 'Mace of the Slave Militia',
        '75': 'Morning Star of the Slave Militia',
        '76': 'Hatchet of the Ash Warden',
        '77': 'Axe of the Ash Warden',
        '78': 'Battle Axe of the Ash Warden',
        '79': 'Short Khopesh of the Warrior',
        '7A': 'Khopesh of the Warrior',
        '7B': 'Long Khopesh of the Warrior',
        '7C': 'Spear of the Anhor Guard',
        '7D': 'Spear of the Anhor Guard',
        '7E': 'Lance of the Anhor Guard',
        '7F': 'Short Bow of the Resheph Chariot',
        '80': 'Bow of the Resheph Chariot',
        '81': 'Long Bow of the Resheph Chariot',
        '82': 'Hatchet of the Mercenary',
        '83': 'Axe of the Mercenary',
        '84': 'Battle Axe of the Mercenary',
        '85': 'Composite Short Bow of the Bowman',
        '86': 'Composite Bow of the Bowman',
        '87': 'Composite Long Bow of the Bowman',
        '88': 'Short Spatha Sword of the Steppe Rider',
        '89': 'Spatha Sword of the Steppe Rider',
        '8A': 'Long Spatha Sword of the Steppe Rider',
        '8B': 'Composite Short Bow of the Marksman',
        '8C': 'Composite Bow of the Marksman',
        '8D': 'Composite Long Bow of the Marksman',
        '8E': 'Short Spatha Sword of the Marauder',
        '8F': 'Spatha Sword of the Marauder',
        '90': 'Long Spatha Sword of the Marauder',
        '3D': 'Small Map',
        '3E': 'Map',
        '3F': 'Large Map',
        '40': 'Small Pennant',
        '41': 'Pennant',
        '42': 'Great Pennant',
        '43': 'Small Standard',
        '44': 'Standard',
        '45': 'Great Standard',
        '49': 'Pouch of the thief',
        '4A': 'Bag of the thief',
        '4B': 'Sack of the thief',
        '4C': 'Small shield',
        '4D': 'Shield',
        '4E': 'Large shield',
        '4F': 'Small horn of the Natarian',
        '50': 'Horn of the Natarian',
        '51': 'Large horn of the Natarian',
        '52': 'Light armour of Regeneration',
        '53': 'Armour of Regeneration',
        '54': 'Heavy armour of Regeneration',
        '55': 'Light scale armour',
        '56': 'Scale armour',
        '57': 'Heavy scale armour',
        '58': 'Light breastplate',
        '59': 'Breastplate',
        '5A': 'Heavy breastplate',
        '5B': 'Light segmented armour',
        '5C': 'Segmented armour',
        '5D': 'Heavy segmented armour',
        '5E': 'Boots of Regeneration',
        '5F': 'Boots of Healthiness',
        '60': 'Boots of Healing',
        '61': 'Boots of the Mercenary',
        '62': 'Boots of the Warrior',
        '63': 'Boots of the Archon',
        '64': 'Small spurs',
        '65': 'Spurs',
        '66': 'Nasty spurs',
        '67': 'Gelding',
        '68': 'Thoroughbred',
        '69': 'Warhorse'}

    items = ''
    for k, v in hero_item_postions.items():
        try:
            items+=(hero_items_dict[hero_items_string[k:k+v].upper()])
            items+='\n'
        except KeyError:
            pass


    embed = discord.Embed(color=success)
    embed.add_field(name="Hero Items", value=items)

    return embed
