CREATE TABLE IF NOT EXISTS NOTIFICATION_SUBSCRIPTIONS (
    GUILD_ID TEXT NOT NULL,
    CHANNEL_ID TEXT NOT NULL,
    NOTIFICATION_CODE TEXT NOT NULL,
    TARGET_ID INTEGER NOT NULL,
    DISCORD_ID TEXT NOT NULL,
    EXTRA_INFO TEXT NOT NULL
    );