CREATE TABLE IF NOT EXISTS DEFENSE_THREADS(
    id INTEGER PRIMARY KEY NOT NULL,
    defense_call_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    jump_url TEXT NOT NULL,
    FOREIGN KEY(defense_call_id) REFERENCES SUBMITTED_DEFENSE(id)
    );