CREATE TABLE IF NOT EXISTS HAMMERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    IGN TEXT NOT NULL,
    LINK TEXT NOT NULL,
    COORDINATES TEXT NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL,
    NOTES TEXT
    );
